name: docker
version: '0.6.0.0'
synopsis: An API client for docker written in Haskell
description: See API documentation below.
category: Network
author:
- Deni Bertovic <deni@denibertovic.com>
- James Parker <jp@jamesparker.me>
maintainer: Deni Bertovic <deni@denibertovic.com>
copyright: BSD3
license: BSD3
github: denibertovic/docker-hs
extra-source-files:
- README.md
dependencies:
- base >=4.7 && <5
- vector
- transformers
library:
  source-dirs: src
  default-extensions:
  - DeriveGeneric
  - OverloadedStrings
  - ScopedTypeVariables
  - ExplicitForAll
  - MultiParamTypeClasses
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - RankNTypes
  - DeriveFunctor
  - FlexibleInstances
  - CPP
  ghc-options:
  - -Wall
  - -fno-warn-name-shadowing
  exposed-modules:
  - Docker.Client
  - Docker.Client.Api
  - Docker.Client.Types
  - Docker.Client.Internal
  - Docker.Client.Http
  - Docker.Client.Utils
  dependencies:
  - aeson >=0.9.0 && <2.0.0
  - blaze-builder >=0.4.0 && <0.5.0
  - bytestring >=0.10.0 && <0.11.0
  - conduit
  - conduit-combinators
  - conduit-extra
  - containers >=0.5.0 && <0.6.0
  - convertible
  - data-default-class >=0.0.1 && <0.2.0
  - directory >=1.2.5.0
  - exceptions
  - filemanip
  - filepath
  - http-client >=0.4.0 && <0.6.0
  - http-conduit
  - http-types >=0.9 && <0.13
  - interpolate
  - monad-control
  - mtl >=2.0.0 && <3.0.0
  - network >=2.6.0
  - resourcet
  - scientific >=0.3.0 && <0.4.0
  - tar
  - temporary
  - text >=1.0.0 && <2.0.0
  - time >=1.5.0 && <1.9.0
  - tls >=1.3.7 && <1.5.0
  - transformers-base
  - unliftio-core >=0.1.0.0 && <0.2.0
  - unordered-containers >=0.2.0 && <0.3.0
  - uuid
  - x509 >=1.6.0 && <1.8.0
  - x509-store >=1.6.0 && <1.8.0
  - x509-system >=1.6.0 && <1.8.0
  - zlib
tests:
  docker-hs-tests:
    main: Tests.hs
    source-dirs: tests
    dependencies:
    - QuickCheck
    - aeson
    - bytestring
    - connection
    - containers
    - directory
    - docker
    - hspec
    - hspec-core
    - hspec-expectations
    - http-client
    - http-client-tls
    - http-types
    - interpolate
    - lens
    - lens-aeson
    - process
    - tasty
    - tasty-hunit
    - tasty-hspec
    - tasty-quickcheck
    - text
    - unordered-containers
stability: experimental
